application: irannewsflash
version: 1-3-shoutbox
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /admin/.*
  script: admin.py
  login: admin

- url: /api/.*
  script: api.py

- url: /.*
  script: inf.py


